### ISSUE TITLE
Hydrocity Crash

### ISSUE THREAD

**Issue by RinMaru** [SonicMastr/Sonic-Mania-Vita#4]
Hydrocity seems to crash allot sometimes freezing the entire system. there is no specific point to repro but running around for 3min usually repros.

**Comment by RinMaru** [comment]
[psp2core-1661657831-0x0000062ec9-eboot.bin.psp2dmp.zip](https://github.com/SonicMastr/Sonic-Mania-Vita/files/9439053/psp2core-1661657831-0x0000062ec9-eboot.bin.psp2dmp.zip)
heres the crash dmp

**Comment by Arcadius2006** [comment]
PLEASE FIX THIS it makes the game literally unplayable

this seems to happen a lot in act 2 specifically, btw
